version: '3.4'

services:
  catalog-mongo:
    container_name: catalog-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  catalog.api:
    container_name: Catalog.API
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://localhost:27017"
    depends_on:
      - catalog-mongo
    ports:
      - "8000:80"
